INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(1, 'AC', 7.00, 'NORTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(2, 'AL', 7.00, 'NORDESTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(3, 'AP', 7.00, 'NORTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(4, 'AM', 7.00, 'NORTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(5, 'BA', 7.00, 'NORDESTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(6, 'CE', 7.00, 'NORDESTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(7, 'DF', 7.00, 'NORTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(8, 'ES', 12.00, 'SUDESTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(9, 'RR', 7.00, 'NORTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(10, 'GO', 7.00, 'NORTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(11, 'MA', 7.00, 'NORDESTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(12, 'MT', 7.00, 'NORTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(13, 'MS', 7.00, 'NORTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(14, 'MG', 12.00, 'SUDESTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(15, 'PA', 7.00, 'NORTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(16, 'PB', 7.00, 'NORDESTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(17, 'PR', 12.00, 'SUL');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(18, 'PE', 7.00, 'NORDESTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(19, 'PI', 7.00, 'NORDESTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(20, 'RJ', 12.00, 'SUDESTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(21, 'RN', 7.00, 'NORDESTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(22, 'RS', 12.00, 'SUL');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(23, 'RO', 7.00, 'NORTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(24, 'TO', 7.00, 'NORTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(25, 'SC', 12.00, 'SUL');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(26, 'SP', 12.00, 'SUDESTE');
INSERT INTO projetofrete.uf
(ID_UF, SIGLA_UF, PERC_ICMS, REGIAO)
VALUES(27, 'SE', 7.00, 'NORDESTE');
